###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: holysprit-phpmyadmin
      environment:
        - MYSQL_DATABASE=holysprit_db
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - PMA_HOST=mysql
      ports:
        - "1001:80"
      volumes:
        - php-mysql-data:/sessions

    mailhog:
      image: mailhog/mailhog:latest
      container_name: holysprit-mailhog
      ports:
        - "1002:8025"

    redis:
      image: redis:alpine
      container_name: holysprit-redis
      ports:
        - "1010:6379"

    mysql:
      image: mysql:5.6.36
      container_name: holysprit-mysql
      working_dir: /application
      volumes:
        - .:/application
        - mysql-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=holysprit_db
        - MYSQL_USER=holysprit_user
        - MYSQL_PASSWORD=holysprit_password
      ports:
        - "1003:3306"

    webserver:
      image: nginx:alpine
      container_name: holysprit-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: holysprit-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

volumes:
  mysql-data:
  php-mysql-data:
